apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neurosense-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - neurosense.example.com
      secretName: neurosense-tls
  rules:
    - host: neurosense.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: neurosense-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: neurosense-backend
                port:
                  number: 5000
